modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lydialib"
issueTrackerURL="https://github.com/Yirmiri/LydiaLib/issues"
logoFile = "icon.png"
authors = "${mod_author}"
description = '''${description}'''

[[mixins]]
config = "lydialib.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
